export const SET_TEST = 'SET_TEST'
// app
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'
export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'
export const SET_LANGUAGE = 'SET_LANGUAGE'
// user
export const SET_CODE = 'SET_CODE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_INTRODUCTION = 'SET_INTRODUCTION'
export const SET_SETTING = 'SET_SETTING'
export const SET_STATUS = 'SET_STATUS'
export const SET_NAME = 'SET_NAME'
export const SET_AVATAR = 'SET_AVATAR'
export const SET_ROLES = 'SET_ROLES'
